# Generated by Django 4.1.1 on 2022-09-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='compĺeted',
            new_name='is_compĺeted',
        ),
    ]
