# Generated by Django 4.1.1 on 2022-09-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_compĺeted',
            new_name='compĺeted',
        ),
    ]
