# Generated by Django 4.1.1 on 2022-09-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_content_task_title_rename_user_task_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
    ]
